# Build, Test, and Deploy Azure Functions App
# This workflow builds, tests, and deploys only the application code
# Infrastructure deployment should be handled separately

name: Build, Test, and Deploy Azure Functions

on:
  push:
    branches: [ master, main ]
    paths:
      - 'Server/**'
      - '.github/workflows/azure-functions-deploy.yml'
      - 'Server.Tests/**'
      - 'CopilotBlazor.sln'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'Server/**'
      - '.github/workflows/azure-functions-deploy.yml'
      - 'Server.Tests/**'
      - 'CopilotBlazor.sln'

permissions:
  id-token: write
  contents: read

jobs:
  # Test job for pull requests - build and test only
  test:
    if: github.event_name == 'pull_request'
    runs-on: windows-latest
    name: Test Azure Functions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore CopilotBlazor.sln

      - name: Build solution
        run: dotnet build CopilotBlazor.sln --configuration Release --no-restore

      - name: Run Server Tests
        run: dotnet test Server.Tests/Server.Tests.csproj --verbosity normal

  # Build and test job for pushes (preparation for deployment)
  build-and-test:
    if: github.event_name == 'push'
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          $baseName = "${{ secrets.AZURE_BASE_NAME }}"
          if ([string]::IsNullOrEmpty($baseName)) {
            Write-Error "AZURE_BASE_NAME secret is required but not set. Please configure this secret in your repository settings."
            exit 1
          }
          echo "AZURE_BASE_NAME=$baseName" >> $env:GITHUB_ENV

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore CopilotBlazor.sln

      - name: Build solution
        run: dotnet build CopilotBlazor.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test CopilotBlazor.sln --verbosity normal

      - name: Publish Azure Function
        run: dotnet publish Server/Server.csproj --configuration Release --output ./publish

  deploy:
    runs-on: windows-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          $baseName = "${{ secrets.AZURE_BASE_NAME }}"
          if ([string]::IsNullOrEmpty($baseName)) {
            Write-Error "AZURE_BASE_NAME secret is required but not set. Please configure this secret in your repository settings."
            exit 1
          }
          echo "AZURE_BASE_NAME=$baseName" >> $env:GITHUB_ENV

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish Azure Function
        run: dotnet publish Server/Server.csproj --configuration Release --output ./publish

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_BASE_NAME }}-func-prod
          package: ./publish
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
