# Deploy Azure Infrastructure with Bicep
# This workflow runs the Bicep deployment on request (workflow_dispatch)

name: Deploy Azure Infra (Bicep)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Generate random suffix
        id: random
        run: |
          $RANDOM_SUFFIX = -join ((48..57) + (97..122) | Get-Random -Count 8 | % {[char]$_})
          $BASE_NAME = "copilotblazor$RANDOM_SUFFIX"
          echo "base_name=$BASE_NAME" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        shell: pwsh

      - name: Ensure Resource Group exists
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group create --name ${{ steps.random.outputs.base_name }} --location westeurope

      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ steps.random.outputs.base_name }}
          template: Infra/main.bicep
          parameters: >
            functionAppName=${{ steps.random.outputs.base_name }} storageAccountName=${{ steps.random.outputs.base_name }} keyVaultName=${{ steps.random.outputs.base_name }}
          failOnStdErr: false
