# Deploy Azure Infrastructure with Bicep
# This workflow runs the Bicep deployment on request (workflow_dispatch)

name: Deploy Azure Infra (Bicep)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Generate random suffix
        id: random
        run: |
          $RANDOM_SUFFIX = -join ((48..57) + (97..122) | Get-Random -Count 6 | % {[char]$_})
          echo "random=$RANDOM_SUFFIX" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        shell: pwsh

      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: infra/main.bicep
          parameters: >-
            functionAppName=${{ secrets.AZURE_RESOURCE_GROUP }}${{ steps.random.outputs.random }} \
            storageAccountName=${{ secrets.AZURE_RESOURCE_GROUP }}${{ steps.random.outputs.random }} \
            keyVaultName=${{ secrets.AZURE_RESOURCE_GROUP }}${{ steps.random.outputs.random }}
          failOnStdErr: false
